experiment:
  name: lci_start_bakery_ab_v0
  geos: [IN, BR, JP]
  unit: session
  split: {control: 0.5, treatment: 0.5}
  intent_filter: start_bakery
  timeline:
    shadow_days: 7
    ramp: [0.01, 0.05, 0.25, 0.50]
    duration_days: 14
metrics:
  primary: ctr_click_rate
  secondary: [scroll_depth_avg, pogo_rate, lci_adoption_rate]
slos:
  latency_p95_ms: 150
  staleness_rate: 0.02
  error_flag_rate_per_hour: 0.01
gates:
  ship: {ctr_rel_lift: ">=0.05", pogo_rel_change: "<= -0.03", p_value: "<=0.05"}
  rollback: ["latency_p95>150ms for 30m", "staleness_rate>2%", "error_flag_rate>1%/h"]
